name: Preview-Link-Generator
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install packages
        run: npm install

      - name: Install bundle
        run: bundle install

      - name: Build the app
        run: jekyll build

      - name: Install Surge
        run: npm install -g surge

      - name: Deploy to surge
        env:
          SURGE_LOGIN: acf@sack.edu.lk
          SURGE_TOKEN: 1da2b7e245328ec0a9f28154b2b4a2e1
          DEPLOY_DOMAIN: https://pr-${{ github.event.number }}-sack-site.surge.sh
        run: surge ./ $DEPLOY_DOMAIN --token $SURGE_TOKEN
